version: '3.8'

services:
  web:
    build: .
    container_name: examples-django-tasklist
    # Geliştirme sunucusunu başlatıyoruz
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
